name: Checkout Code from Another Repo

on:
  workflow_dispatch:  # Add this line to allow manual triggering

jobs:
  call-workflow-passing-data:
    uses: L-Quibiq/Central/.github/workflows/hello-world.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: adjhakdfhsdufhsnvj
