name: Deploy Logic App with Params

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  prepare-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read appsettings.json
        id: read_appsettings
        run: |
          appsettings=$(cat iac/parameters/appsettings.json)
          echo "APPSETTINGS_JSON=${appsettings}" >> $GITHUB_ENV

  call-workflow-passing-data:
    needs: prepare-and-deploy
    uses: L-Quibiq/Central/.github/workflows/logic-app-deployment.yml@main
    with:
      appsettings-json: ${{ needs.prepare-and-deploy.outputs.APPSETTINGS_JSON }}
    secrets: inherit
